spring:
  datasource:
    name: move-on
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/move-on
    username: root
    password: 1234
  jpa:
    generate-ddl: true
    database: mysql
    hibernate:
      ddl-auto: create-drop





---
spring:
  config:
    activate:
      on-profile: prod